<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GameManaged>$(HOME)/Library/Application Support/Steam/steamapps/common/Valheim/Valheim.app/Contents/Resources/Data/Managed</GameManaged>
    <BepInExCore>$(HOME)/Library/Application Support/Steam/steamapps/common/Valheim/BepInEx/core</BepInExCore>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ValheimFortress/ValheimFortress.csproj" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="BepInEx" HintPath="$(BepInExCore)/BepInEx.dll" Private="false" />
    <Reference Include="$(GameManaged)/UnityEngine*.dll" Private="false" />
    <Reference Include="$(GameManaged)/publicized_assemblies/*_publicized.dll" Private="false" />
  </ItemGroup>
</Project>
